theme: jekyll-theme-cayman
show_downloads: ['true']
title: Infoooze
description: Infoooze is an Information collection tool (OSINT) in NodeJs. It provides various modules that allow efficient searches.
author: Prateek Singh
email: bhps82@gmail.com
google_analytics: G-V5FE6XQHBW